version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Taipei
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # command: ["flask", "--app", "app:app", "run", "--debug", "--host=0.0.0.0", "--port=8000"]
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: user
      TZ: Asia/Taipei
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
      TZ: Asia/Taipei

volumes:
  mysql-data:
  minio_data: