"""add status for job

Revision ID: 221bb6cbb032
Revises: 49ba79d7906a
Create Date: 2025-09-20 13:29:04.689487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221bb6cbb032'
down_revision = '49ba79d7906a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='jobstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
