"""add job application

Revision ID: 49ba79d7906a
Revises: fbc0cf1a3b29
Create Date: 2025-09-20 10:10:16.468711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ba79d7906a'
down_revision = 'fbc0cf1a3b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('applicant_id', 'job_id', name='unique_user_job_application')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    # ### end Alembic commands ###
