"""add filename in job

Revision ID: c57b3cdc18bb
Revises: 1ccde89a62f7
Create Date: 2025-09-21 03:18:47.807116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57b3cdc18bb'
down_revision = '1ccde89a62f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
