"""create job table

Revision ID: fbc0cf1a3b29
Revises: d22f2a05ab08
Create Date: 2025-09-20 01:16:46.817104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc0cf1a3b29'
down_revision = 'd22f2a05ab08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('payment_low', sa.Integer(), nullable=False),
    sa.Column('payment_high', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
